# Generated by Django 4.2.3 on 2023-07-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identification", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("roof", models.CharField(max_length=255)),
                ("connection", models.CharField(max_length=255)),
                ("maximum_overload", models.PositiveIntegerField()),
                ("kwp", models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="KitCable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="KitConnectorPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="KitInverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="KitModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="KitStringBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="KitStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("power", models.PositiveIntegerField()),
                ("brand", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StringBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("model", "power", "brand"), name="unique_model_power_brand"
            ),
        ),
        migrations.AddField(
            model_name="kitstructure",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_structures",
                to="core.kit",
            ),
        ),
        migrations.AddField(
            model_name="kitstructure",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_structures",
                to="core.structure",
            ),
        ),
        migrations.AddField(
            model_name="kitstringbox",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_string_boxes",
                to="core.kit",
            ),
        ),
        migrations.AddField(
            model_name="kitstringbox",
            name="string_box",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_string_boxes",
                to="core.stringbox",
            ),
        ),
        migrations.AddField(
            model_name="kitmodule",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_modules",
                to="core.kit",
            ),
        ),
        migrations.AddField(
            model_name="kitmodule",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_modules",
                to="core.module",
            ),
        ),
        migrations.AddField(
            model_name="kitinverter",
            name="inverter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_inverters",
                to="core.inverter",
            ),
        ),
        migrations.AddField(
            model_name="kitinverter",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_inverters",
                to="core.kit",
            ),
        ),
        migrations.AddField(
            model_name="kitconnectorpair",
            name="connector_pair",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_connector_pairs",
                to="core.connectorpair",
            ),
        ),
        migrations.AddField(
            model_name="kitconnectorpair",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_connector_pairs",
                to="core.kit",
            ),
        ),
        migrations.AddField(
            model_name="kitcable",
            name="cable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_cables",
                to="core.cable",
            ),
        ),
        migrations.AddField(
            model_name="kitcable",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_cables",
                to="core.kit",
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="cables",
            field=models.ManyToManyField(
                related_name="kits", through="core.KitCable", to="core.cable"
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="connector_pairs",
            field=models.ManyToManyField(
                related_name="kits",
                through="core.KitConnectorPair",
                to="core.connectorpair",
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="inverters",
            field=models.ManyToManyField(
                related_name="kits", through="core.KitInverter", to="core.inverter"
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="modules",
            field=models.ManyToManyField(
                related_name="kits", through="core.KitModule", to="core.module"
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="string_boxes",
            field=models.ManyToManyField(
                related_name="kits", through="core.KitStringBox", to="core.stringbox"
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="structures",
            field=models.ManyToManyField(
                related_name="kits", through="core.KitStructure", to="core.structure"
            ),
        ),
        migrations.AddConstraint(
            model_name="inverter",
            constraint=models.UniqueConstraint(
                fields=("name", "brand"), name="unique_name_brand"
            ),
        ),
        migrations.AddConstraint(
            model_name="kitstructure",
            constraint=models.UniqueConstraint(
                fields=("kit", "structure"), name="unique_kit_structure"
            ),
        ),
        migrations.AddConstraint(
            model_name="kitstringbox",
            constraint=models.UniqueConstraint(
                fields=("kit", "string_box"), name="unique_kit_stringbox"
            ),
        ),
        migrations.AddConstraint(
            model_name="kitmodule",
            constraint=models.UniqueConstraint(
                fields=("kit", "module"), name="unique_kit_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="kitinverter",
            constraint=models.UniqueConstraint(
                fields=("kit", "inverter"), name="unique_kit_inverter"
            ),
        ),
        migrations.AddConstraint(
            model_name="kitconnectorpair",
            constraint=models.UniqueConstraint(
                fields=("kit", "connector_pair"), name="unique_kit_connectorpair"
            ),
        ),
        migrations.AddConstraint(
            model_name="kitcable",
            constraint=models.UniqueConstraint(
                fields=("kit", "cable"), name="unique_kit_cable"
            ),
        ),
    ]
